# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: part_one.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='part_one.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0epart_one.proto\"c\n\rTaxiSolicitud\x12\x0f\n\x07taxi_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63onductor_id\x18\x02 \x01(\t\x12\x13\n\x0bpasajero_id\x18\x03 \x03(\t\x12\x16\n\x0e\x63osto_estimado\x18\x04 \x01(\x02\x62\x06proto3'
)




_TAXISOLICITUD = _descriptor.Descriptor(
  name='TaxiSolicitud',
  full_name='TaxiSolicitud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taxi_id', full_name='TaxiSolicitud.taxi_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conductor_id', full_name='TaxiSolicitud.conductor_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pasajero_id', full_name='TaxiSolicitud.pasajero_id', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='costo_estimado', full_name='TaxiSolicitud.costo_estimado', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['TaxiSolicitud'] = _TAXISOLICITUD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaxiSolicitud = _reflection.GeneratedProtocolMessageType('TaxiSolicitud', (_message.Message,), {
  'DESCRIPTOR' : _TAXISOLICITUD,
  '__module__' : 'part_one_pb2'
  # @@protoc_insertion_point(class_scope:TaxiSolicitud)
  })
_sym_db.RegisterMessage(TaxiSolicitud)


# @@protoc_insertion_point(module_scope)
